#!/usr/bin/env python3
"""
Build script: reference/tcm-data-tier1.xlsx → backend/app/Services/WellnessAssessment/data/TreatmentBank.php

Reads three sheets (Syndromes, Formulas, RedFlags) from the curated tier-1
data and bakes them into a PHP constant class. Run this whenever the
spreadsheet changes:

    cd reference && python3 _build_treatment_bank.py

Output is a single self-contained PHP file with three public constants:
SYNDROMES, FORMULAS, REDFLAGS. No runtime XLSX reading — fast + no extra
PHP deps.
"""
import openpyxl, json, os, re

XLSX = os.path.join(os.path.dirname(__file__), 'tcm-data-tier1.xlsx')
OUT  = os.path.join(os.path.dirname(__file__), '..', 'backend', 'app',
                    'Services', 'WellnessAssessment', 'data', 'TreatmentBank.php')

wb = openpyxl.load_workbook(XLSX, data_only=True)

def rows_as_dicts(sheet):
    ws = wb[sheet]
    headers = [c.value for c in ws[1]]
    out = []
    for r in range(2, ws.max_row + 1):
        row = {h: ws.cell(row=r, column=i+1).value for i, h in enumerate(headers) if h}
        if any(row.values()):
            out.append(row)
    return out

# ── Build PHP arrays ───────────────────────────────────────────
def to_php_value(v, indent=8):
    pad = " " * indent
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        if not v:
            return "[]"
        inner = ",\n".join(pad + "    " + to_php_value(x, indent+4) for x in v)
        return "[\n" + inner + "\n" + pad + "]"
    if isinstance(v, dict):
        if not v:
            return "[]"
        items = []
        for k, val in v.items():
            items.append(pad + "    " + repr(str(k)).replace("\\", "\\\\") + " => " + to_php_value(val, indent+4))
        return "[\n" + ",\n".join(items) + "\n" + pad + "]"
    s = str(v).replace("\\", "\\\\").replace("'", "\\'")
    return "'" + s + "'"

# Syndromes — keyed by ID, value = dict of fields
syndromes_raw = rows_as_dicts("Syndromes")
syndromes = {}
for r in syndromes_raw:
    sid = r.get("ID")
    if not sid: continue
    syndromes[sid] = {
        "id":                  sid,
        "name_en":             r.get("EN Name"),
        "name_zh":             r.get("ZH Name"),
        "pinyin":              r.get("PY"),
        "category":            r.get("Category"),
        "primary_symptoms":    r.get("Primary Symptoms (主證)"),
        "secondary_symptoms":  r.get("Secondary Symptoms (次證)"),
        "tongue":              r.get("Tongue (舌象)"),
        "pulse":               r.get("Pulse (脈象)"),
        "treatment_principle": r.get("Treatment Principle (治法)"),
        "default_formulas":    r.get("Default Formula(s)"),
        "source":              r.get("Source"),
        "notes":               r.get("Notes"),
    }

# Formulas — keyed by ZH name for fast lookup from syndrome's default_formulas
formulas_raw = rows_as_dicts("Formulas")
formulas = {}
for r in formulas_raw:
    zh = r.get("ZH Name") or r.get("Name")
    if not zh: continue
    formulas[zh] = { (k.lower().replace(" ", "_").replace("(", "").replace(")", "")): v for k, v in r.items() if v is not None }

# RedFlags — keyed by RF-ID. avoid_herbs[] parsed from the semicolon-separated text.
redflags_raw = rows_as_dicts("RedFlags")
redflags = {}
for r in redflags_raw:
    rid = r.get("ID")
    if not rid: continue
    avoid_raw = r.get("Avoid Herbs / Formulas") or ""
    avoid_list = [a.strip() for a in re.split(r"[;,，；]", str(avoid_raw)) if a.strip()]
    redflags[rid] = {
        "id":          rid,
        "type":        r.get("Type"),
        "condition":   r.get("Condition / Drug"),
        "avoid_herbs": avoid_list,
        "reason":      r.get("Reason"),
        "severity":    r.get("Severity"),
        "notes":       r.get("Notes for Malaysian context") or r.get("Notes"),
    }

# ── Emit PHP ───────────────────────────────────────────
php = ["<?php"]
php.append("")
php.append("// AUTO-GENERATED by reference/_build_treatment_bank.py")
php.append("// DO NOT EDIT BY HAND. Edit the tier-1 spreadsheet then re-run the script.")
php.append("// Source: reference/tcm-data-tier1.xlsx")
php.append("")
php.append("namespace App\Services\WellnessAssessment\data;")
php.append("")
php.append("/**")
php.append(" * Brief #22 · curated TCM treatment data baked from the tier-1 spreadsheet.")
php.append(" * Read by TreatmentSuggester to propose a classical formula starting point")
php.append(" * for the doctor's pre-assessment review.")
php.append(" *")
php.append(" * All content is public-domain classical TCM (傷寒論, 金匱要略 era, 1000+ years).")
php.append(" * Modifications driven by the RedFlags rules below.")
php.append(" */")
php.append("class TreatmentBank")
php.append("{")
php.append("    public const SYNDROMES = " + to_php_value(syndromes, 4) + ";")
php.append("")
php.append("    public const FORMULAS = " + to_php_value(formulas, 4) + ";")
php.append("")
php.append("    public const REDFLAGS = " + to_php_value(redflags, 4) + ";")
php.append("}")
php.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(php))

print(f"Wrote {OUT}")
print(f"  · {len(syndromes)} syndromes")
print(f"  · {len(formulas)} formulas")
print(f"  · {len(redflags)} red flags")
