<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Prescription · 處方箋</title>
<style>
  @page { size: A4; margin: 15mm; }
  body { font-family: 'Segoe UI', 'Noto Sans SC', sans-serif; font-size: 11pt; color: #333; margin: 0; padding: 20px; }
  .header { text-align: center; border-bottom: 2px solid #b8965a; padding-bottom: 15px; margin-bottom: 20px; }
  .clinic-name { font-size: 18pt; font-weight: 600; color: #1a1612; }
  .clinic-name-zh { font-size: 14pt; color: #7a7068; }
  .doc-label { font-size: 8pt; letter-spacing: 2px; text-transform: uppercase; color: #b8965a; margin-bottom: 3px; }
  .doc-title { font-size: 16pt; color: #1a1612; text-align: center; margin: 15px 0; }
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 15px; }
  .info-item { font-size: 10pt; }
  .info-label { color: #b8965a; font-size: 8pt; text-transform: uppercase; letter-spacing: 1px; }
  table { width: 100%; border-collapse: collapse; margin: 15px 0; }
  th { background: #f5f0e8; font-size: 9pt; text-transform: uppercase; letter-spacing: 1px; color: #7a7068; padding: 8px; text-align: left; border-bottom: 2px solid #b8965a; }
  td { padding: 8px; border-bottom: 1px solid #ede7d8; font-size: 10pt; }
  .footer { margin-top: 40px; display: flex; justify-content: space-between; }
  .signature { border-top: 1px solid #333; padding-top: 5px; width: 200px; text-align: center; font-size: 9pt; color: #7a7068; }
  .instructions { background: #f5f0e8; padding: 12px; margin: 15px 0; border-left: 3px solid #b8965a; font-size: 10pt; }
  @media print { body { padding: 0; } button { display: none !important; } }
</style>
</head>
<body>
<div class="header">
  <div class="clinic-name">HansMed Modern TCM</div>
  <div class="clinic-name-zh">漢方現代中醫</div>
  <div style="font-size: 9pt; color: #7a7068; margin-top: 5px;">Traditional Chinese Medicine · Telehealth & Clinic</div>
</div>

<div class="doc-title">PRESCRIPTION · 處方箋</div>

<div class="info-grid">
  <div class="info-item"><div class="info-label">Patient · 患者</div>{{ $patient->full_name ?? $patient->nickname ?? 'N/A' }}</div>
  <div class="info-item"><div class="info-label">Date · 日期</div>{{ $rx->issued_at?->format('d M Y') ?? $rx->created_at->format('d M Y') }}</div>
  <div class="info-item"><div class="info-label">IC / ID</div>{{ $patient->ic_number ?? 'N/A' }}</div>
  <div class="info-item"><div class="info-label">Rx No.</div>HM-RX-{{ str_pad($rx->id, 6, '0', STR_PAD_LEFT) }}</div>
  <div class="info-item"><div class="info-label">Doctor · 醫師</div>{{ $doctor->full_name ?? 'N/A' }} ({{ $doctor->license_no ?? '' }})</div>
  <div class="info-item"><div class="info-label">Duration · 療程</div>{{ $rx->duration_days ?? 'N/A' }} days</div>
</div>

<div class="info-item" style="margin-bottom: 10px;"><div class="info-label">Diagnosis · 診斷</div>{{ $rx->diagnosis ?? 'N/A' }}</div>

<table>
  <thead><tr><th>#</th><th>Drug Name · 藥名</th><th>Spec</th><th>Dosage</th><th>Qty</th><th>Unit</th><th>Usage</th></tr></thead>
  <tbody>
  @foreach ($rx->items as $i => $item)
    <tr>
      <td>{{ $i + 1 }}</td>
      <td>{{ $item->drug_name }}</td>
      <td>{{ $item->specification ?? '—' }}</td>
      <td>{{ $item->dosage ?? '—' }}</td>
      <td>{{ $item->quantity }}</td>
      <td>{{ $item->unit }}</td>
      <td>{{ $item->usage_method ?? $item->frequency ?? '—' }}</td>
    </tr>
  @endforeach
  </tbody>
</table>

@if ($rx->instructions)
<div class="instructions">
  <div class="info-label">Instructions · 醫囑</div>
  {{ $rx->instructions }}
</div>
@endif

@if ($rx->contraindications)
<div class="instructions" style="border-left-color: #c0392b;">
  <div class="info-label" style="color: #c0392b;">Contraindications · 禁忌</div>
  {{ $rx->contraindications }}
</div>
@endif

<div class="footer">
  <div class="signature">Doctor's Signature · 醫師簽章<br><br><strong>{{ $doctor->full_name ?? '' }}</strong></div>
  <div style="text-align: right; font-size: 8pt; color: #999;">Generated by HansMed System<br>{{ now()->format('d M Y H:i') }}</div>
</div>

<button onclick="window.print()" style="position:fixed;bottom:20px;right:20px;padding:10px 25px;background:#1a1612;color:#f5f0e8;border:none;cursor:pointer;font-size:12px;letter-spacing:2px;">PRINT · 列印</button>
</body>
</html>
